### ISSUE TITLE
ITI-65 structureDefinitions should forbid entryUUID

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#167]

**Comment by JohnMoehrke** [comment]
ITI-Tech committee discussion -> change sentence

The Documet Recipient shall create missing entryUUID values where necessary to satisfy XDS requirements.

to

Except that the Document Source does not need to provide any entryUUID values, as the entryUUID will be populated by the Document Recipient when necessary.

**Comment by JohnMoehrke** [comment]
make change to master and improvements branches

**Comment by JohnMoehrke** [comment]
Given that the entryUUID is a uniquely SOAP ebRegistry attribute. There is no way for a MHD Document Source to be able to generate it. Further in a case that does not have XDS Registry, there is no value to providing one.

**Comment by skbhaskarla** [comment]
> 

Technically, the MHD 4.2.0 SubmissionSet resource profile StructureDefinition allows an entryUUID, so when this value is present, what is the expected behavior? (In XDS.b, the entryUUID carries a special significance in that, when not symbolic, the registry uses the same entryUUID for the registry object being created.)

Another question, why is now the MHD SubmissionSet [uniqueId](https://profiles.ihe.net/ITI/MHD/4.2.0/StructureDefinition-IHE.MHD.Minimal.SubmissionSet-definitions.html#List.identifier:uniqueId) cardinality allow a minimum of 0? Why was this changed from 1..1 (MHD 4.1.0)?

**Comment by JohnMoehrke** [comment]
I would guess the same rational. In a pure FHIR environment (MHDS) there is no value to these.

**Comment by skbhaskarla** [comment]
> I would guess the same rational. In a pure FHIR environment (MHDS) there is no value to these.

When there is no value, why do these elements exist in the MHD StructureDefinition?

**Comment by skbhaskarla** [comment]
SubmissionSet uniqueId is a separate question, a value must be provided and cannot be symbolic in XDS.b.

**Comment by JohnMoehrke** [comment]
I think we expected that the Document Recipient that is grouped with Document Sharing Profiles would do the right thing. Trying to define the algorithm is not our goal.
https://profiles.ihe.net/ITI/MHD/ITI-65.html#23654131-grouping-with-actors-in-other-document-sharing-profiles

> The Document Recipient shall create appropriate metadata from Resources in the FHIR Bundle Resource, including SubmissionSet, DocumentEntry, Folder, and Associations.
