### ISSUE TITLE
Access to IG artifacts should be through transaction specifications

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#54]
**Section Number** general

**Issue** Context for requirements; navigation

**Proposed Change** The more time I spend in this IG, the more I think that the access to the artifacts like structure definitions, capability statements, and mappings needs to be from within a transaction and not from Vol 1.   When you are in the transaction, you have the context  for the actor (sender or receiver) and the message semantics (req/rsp), and then the links to the artifacts make sense.   Every time I landed in a CapabilityStatement from a link in Vol 1, I felt like I stepped into a black hole

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by costateixeira** [comment]
I agree with this. The artifacts list is a flat list and not very easy to
navigate.
My thinking today is that we should start from the transaction page and
where applicable, there should be a link to the profile - see for example
the link to [S1] in the diagram in this otherwise empty page:
http://build.fhir.org/ig/IHE/pharm-supply/branches/master/resupply_order.html

**Comment by JohnMoehrke** [comment]
Lynn, which artifacts did you find in the Volume 1 material. The only one that I think I have there is the CapabilityStatement. The reason for this is that the CapabilityStatement is the definition of the Actor... On this topic, I would agree that it is less helpful in Volume 1 than I might have thought it was.

You should not have found any StructureDefinitions in Volume 1.

**Comment by JohnMoehrke** [comment]
clarified the links to the capability statements are specifically capability statements.
