### ISSUE TITLE
List/submission set extension definitions

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#68]
**Section Number** https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Comprehensive.SubmissionSet.html and https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Minimal.SubmissionSet.html

**Issue** We have added extensions to List/submission set for attributes in XDS submission set metadata.  Why not re-use the definitions for those attributes as used in XDS submission set?     It took me a few clicks to figure out that extension:designationType was contentTypeCode

Also, List.source.ihe-authorOrg is a Reference(Organization), but XDS SubmissionSet.author is defined as "The humans and/or machines that authored the SubmissionSet. "   and your mapping reads "SubmissionSet.author when the author is an Organization".   What about when the author is not an organization?

**Proposed Change** We have fine definitions in Vol 3 section 4.1.3.3.  Why not reuse them?

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
When author is not an organization the .source element is used. The extension ihe-authorOrg is only used when the author is an organization because that is not allowed in the .source element.

designationType has different meanings from SubmissionSet vs Folder. Thus it is the same element with different purpose.

I will try to give some clarity.
